// Generated by scripts/generate_backend.py.
import Foundation
final class AuroraBackend {
    var context:UnsafeMutableRawPointer?
    init(context:UnsafeMutableRawPointer?=nil){self.context=context}
    var isPlugin:Bool{context != nil}
    func aurora_initialize() -> Void {
#if AURORA_PLUGIN
        return aurora_plugin_initialize(context)
#else
        return aurora_initializeStandalone()
#endif
    }
    func aurora_shutdown() -> Void {
#if AURORA_PLUGIN
        return aurora_plugin_shutdown(context)
#else
        return aurora_shutdownStandalone()
#endif
    }
    func aurora_refresh_devices() -> Void {
#if AURORA_PLUGIN
        return aurora_plugin_refresh_devices(context)
#else
        return aurora_refresh_devicesStandalone()
#endif
    }
    func aurora_audio_devices_json() -> UnsafePointer<CChar>! {
#if AURORA_PLUGIN
        return aurora_plugin_audio_devices_json(context)
#else
        return aurora_audio_devices_jsonStandalone()
#endif
    }
    func aurora_midi_sources_json() -> UnsafePointer<CChar>! {
#if AURORA_PLUGIN
        return aurora_plugin_midi_sources_json(context)
#else
        return aurora_midi_sources_jsonStandalone()
#endif
    }
    func aurora_status() -> UnsafePointer<CChar>! {
#if AURORA_PLUGIN
        return aurora_plugin_status(context)
#else
        return aurora_statusStandalone()
#endif
    }
    func aurora_start_audio(_ deviceID: UInt32, _ bufferFrames: UInt32) -> Int32 {
#if AURORA_PLUGIN
        return aurora_plugin_start_audio(context, deviceID, bufferFrames)
#else
        return aurora_start_audioStandalone(deviceID, bufferFrames)
#endif
    }
    func aurora_stop_audio() -> Void {
#if AURORA_PLUGIN
        return aurora_plugin_stop_audio(context)
#else
        return aurora_stop_audioStandalone()
#endif
    }
    func aurora_audio_running() -> Int32 {
#if AURORA_PLUGIN
        return aurora_plugin_audio_running(context)
#else
        return aurora_audio_runningStandalone()
#endif
    }
    func aurora_current_device() -> UInt32 {
#if AURORA_PLUGIN
        return aurora_plugin_current_device(context)
#else
        return aurora_current_deviceStandalone()
#endif
    }
    func aurora_sample_rate() -> Double {
#if AURORA_PLUGIN
        return aurora_plugin_sample_rate(context)
#else
        return aurora_sample_rateStandalone()
#endif
    }
    func aurora_buffer_frames() -> UInt32 {
#if AURORA_PLUGIN
        return aurora_plugin_buffer_frames(context)
#else
        return aurora_buffer_framesStandalone()
#endif
    }
    func aurora_set_parameter(_ layer: Int32, _ parameter: Int32, _ value: Float) -> Void {
#if AURORA_PLUGIN
        return aurora_plugin_set_parameter(context, layer, parameter, value)
#else
        return aurora_set_parameterStandalone(layer, parameter, value)
#endif
    }
    func aurora_get_parameter(_ layer: Int32, _ parameter: Int32) -> Float {
#if AURORA_PLUGIN
        return aurora_plugin_get_parameter(context, layer, parameter)
#else
        return aurora_get_parameterStandalone(layer, parameter)
#endif
    }
    func aurora_set_layer_fm(_ layer: Int32, _ data: UnsafePointer<Float>?, _ count: Int32) -> Void {
#if AURORA_PLUGIN
        return aurora_plugin_set_layer_fm(context, layer, data, count)
#else
        return aurora_set_layer_fmStandalone(layer, data, count)
#endif
    }
    func aurora_set_matrix(_ bank: Int32, _ slot: Int32, _ enabled: Int32, _ source: Int32, _ destination: Int32, _ target: Int32, _ cc: Int32, _ amount: Float) -> Void {
#if AURORA_PLUGIN
        return aurora_plugin_set_matrix(context, bank, slot, enabled, source, destination, target, cc, amount)
#else
        return aurora_set_matrixStandalone(bank, slot, enabled, source, destination, target, cc, amount)
#endif
    }
    func aurora_set_motion(_ layer: Int32, _ data: UnsafePointer<Float>?, _ count: Int32) -> Int32 {
#if AURORA_PLUGIN
        return aurora_plugin_set_motion(context, layer, data, count)
#else
        return aurora_set_motionStandalone(layer, data, count)
#endif
    }
    func aurora_motion_phase(_ layer: Int32) -> Float {
#if AURORA_PLUGIN
        return aurora_plugin_motion_phase(context, layer)
#else
        return aurora_motion_phaseStandalone(layer)
#endif
    }
    func aurora_layer_sends(_ layer: Int32, _ delay: Float, _ reverb: Float, _ shimmer: Float) -> Void {
#if AURORA_PLUGIN
        return aurora_plugin_layer_sends(context, layer, delay, reverb, shimmer)
#else
        return aurora_layer_sendsStandalone(layer, delay, reverb, shimmer)
#endif
    }
    func aurora_solo_layer(_ layer: Int32) -> Void {
#if AURORA_PLUGIN
        return aurora_plugin_solo_layer(context, layer)
#else
        return aurora_solo_layerStandalone(layer)
#endif
    }
    func aurora_set_transpose(_ semitones: Int32) -> Void {
#if AURORA_PLUGIN
        return aurora_plugin_set_transpose(context, semitones)
#else
        return aurora_set_transposeStandalone(semitones)
#endif
    }
    func aurora_set_global(_ parameter: Int32, _ value: Float) -> Void {
#if AURORA_PLUGIN
        return aurora_plugin_set_global(context, parameter, value)
#else
        return aurora_set_globalStandalone(parameter, value)
#endif
    }
    func aurora_get_global(_ parameter: Int32) -> Float {
#if AURORA_PLUGIN
        return aurora_plugin_get_global(context, parameter)
#else
        return aurora_get_globalStandalone(parameter)
#endif
    }
    func aurora_route_source(_ sourceID: Int32, _ layerMask: Int32, _ channel: Int32) -> Void {
#if AURORA_PLUGIN
        return aurora_plugin_route_source(context, sourceID, layerMask, channel)
#else
        return aurora_route_sourceStandalone(sourceID, layerMask, channel)
#endif
    }
    func aurora_velocity_curve(_ sourceID: Int32, _ curve: Int32) -> Void {
#if AURORA_PLUGIN
        return aurora_plugin_velocity_curve(context, sourceID, curve)
#else
        return aurora_velocity_curveStandalone(sourceID, curve)
#endif
    }
    func aurora_hold(_ enabled: Int32) -> Void {
#if AURORA_PLUGIN
        return aurora_plugin_hold(context, enabled)
#else
        return aurora_holdStandalone(enabled)
#endif
    }
    func aurora_clock_source(_ enabled: Int32, _ sourceID: Int32) -> Void {
#if AURORA_PLUGIN
        return aurora_plugin_clock_source(context, enabled, sourceID)
#else
        return aurora_clock_sourceStandalone(enabled, sourceID)
#endif
    }
    func aurora_clock_tempo() -> Float {
#if AURORA_PLUGIN
        return aurora_plugin_clock_tempo(context)
#else
        return aurora_clock_tempoStandalone()
#endif
    }
    func aurora_record_start(_ path: String) -> Int32 {
#if AURORA_PLUGIN
        return aurora_plugin_record_start(context, path)
#else
        return aurora_record_startStandalone(path)
#endif
    }
    func aurora_record_stop() -> Int32 {
#if AURORA_PLUGIN
        return aurora_plugin_record_stop(context)
#else
        return aurora_record_stopStandalone()
#endif
    }
    func aurora_recording() -> Int32 {
#if AURORA_PLUGIN
        return aurora_plugin_recording(context)
#else
        return aurora_recordingStandalone()
#endif
    }
    func aurora_record_seconds() -> Double {
#if AURORA_PLUGIN
        return aurora_plugin_record_seconds(context)
#else
        return aurora_record_secondsStandalone()
#endif
    }
    func aurora_note_on(_ note: Int32, _ velocity: Int32) -> Void {
#if AURORA_PLUGIN
        return aurora_plugin_note_on(context, note, velocity)
#else
        return aurora_note_onStandalone(note, velocity)
#endif
    }
    func aurora_note_off(_ note: Int32) -> Void {
#if AURORA_PLUGIN
        return aurora_plugin_note_off(context, note)
#else
        return aurora_note_offStandalone(note)
#endif
    }
    func aurora_panic() -> Void {
#if AURORA_PLUGIN
        return aurora_plugin_panic(context)
#else
        return aurora_panicStandalone()
#endif
    }
    func aurora_output_peak() -> Float {
#if AURORA_PLUGIN
        return aurora_plugin_output_peak(context)
#else
        return aurora_output_peakStandalone()
#endif
    }
    func aurora_comp_gr() -> Float {
#if AURORA_PLUGIN
        return aurora_plugin_comp_gr(context)
#else
        return aurora_comp_grStandalone()
#endif
    }
    func aurora_copy_scope(_ samples: UnsafeMutablePointer<Float>?, _ capacity: Int32) -> Int32 {
#if AURORA_PLUGIN
        return aurora_plugin_copy_scope(context, samples, capacity)
#else
        return aurora_copy_scopeStandalone(samples, capacity)
#endif
    }
    func aurora_copy_modulation(_ values: UnsafeMutablePointer<Float>?, _ capacity: Int32) -> Int32 {
#if AURORA_PLUGIN
        return aurora_plugin_copy_modulation(context, values, capacity)
#else
        return aurora_copy_modulationStandalone(values, capacity)
#endif
    }
    func aurora_set_custom_wavetable(_ layer: Int32, _ oscillator: Int32, _ samples: UnsafePointer<Float>?, _ frames: Int32, _ frameSize: Int32) -> Int32 {
#if AURORA_PLUGIN
        return aurora_plugin_set_custom_wavetable(context, layer, oscillator, samples, frames, frameSize)
#else
        return aurora_set_custom_wavetableStandalone(layer, oscillator, samples, frames, frameSize)
#endif
    }
    func aurora_clear_custom_wavetable(_ layer: Int32, _ oscillator: Int32) -> Void {
#if AURORA_PLUGIN
        return aurora_plugin_clear_custom_wavetable(context, layer, oscillator)
#else
        return aurora_clear_custom_wavetableStandalone(layer, oscillator)
#endif
    }
    func aurora_copy_wavetable_preview(_ layer: Int32, _ oscillator: Int32, _ samples: UnsafeMutablePointer<Float>?, _ capacity: Int32) -> Int32 {
#if AURORA_PLUGIN
        return aurora_plugin_copy_wavetable_preview(context, layer, oscillator, samples, capacity)
#else
        return aurora_copy_wavetable_previewStandalone(layer, oscillator, samples, capacity)
#endif
    }
    func aurora_cpu_load() -> Float {
#if AURORA_PLUGIN
        return aurora_plugin_cpu_load(context)
#else
        return aurora_cpu_loadStandalone()
#endif
    }
    func aurora_active_voices() -> Int32 {
#if AURORA_PLUGIN
        return aurora_plugin_active_voices(context)
#else
        return aurora_active_voicesStandalone()
#endif
    }
    func aurora_midi_event_count() -> UInt64 {
#if AURORA_PLUGIN
        return aurora_plugin_midi_event_count(context)
#else
        return aurora_midi_event_countStandalone()
#endif
    }
    func aurora_last_cc() -> Int64 {
#if AURORA_PLUGIN
        return aurora_plugin_last_cc(context)
#else
        return aurora_last_ccStandalone()
#endif
    }
    func aurora_last_cc_source() -> Int32 {
#if AURORA_PLUGIN
        return aurora_plugin_last_cc_source(context)
#else
        return aurora_last_cc_sourceStandalone()
#endif
    }
    func aurora_cc_count() -> UInt64 {
#if AURORA_PLUGIN
        return aurora_plugin_cc_count(context)
#else
        return aurora_cc_countStandalone()
#endif
    }
    func aurora_last_cc_snapshot() -> UInt64 {
#if AURORA_PLUGIN
        return aurora_plugin_last_cc_snapshot(context)
#else
        return aurora_last_cc_snapshotStandalone()
#endif
    }
}
#if !AURORA_PLUGIN
private let aurora_initializeStandalone = aurora_initialize
private let aurora_shutdownStandalone = aurora_shutdown
private let aurora_refresh_devicesStandalone = aurora_refresh_devices
private let aurora_audio_devices_jsonStandalone = aurora_audio_devices_json
private let aurora_midi_sources_jsonStandalone = aurora_midi_sources_json
private let aurora_statusStandalone = aurora_status
private let aurora_start_audioStandalone = aurora_start_audio
private let aurora_stop_audioStandalone = aurora_stop_audio
private let aurora_audio_runningStandalone = aurora_audio_running
private let aurora_current_deviceStandalone = aurora_current_device
private let aurora_sample_rateStandalone = aurora_sample_rate
private let aurora_buffer_framesStandalone = aurora_buffer_frames
private let aurora_set_parameterStandalone = aurora_set_parameter
private let aurora_get_parameterStandalone = aurora_get_parameter
private let aurora_set_layer_fmStandalone = aurora_set_layer_fm
private let aurora_set_matrixStandalone = aurora_set_matrix
private let aurora_set_motionStandalone = aurora_set_motion
private let aurora_motion_phaseStandalone = aurora_motion_phase
private let aurora_layer_sendsStandalone = aurora_layer_sends
private let aurora_solo_layerStandalone = aurora_solo_layer
private let aurora_set_transposeStandalone = aurora_set_transpose
private let aurora_set_globalStandalone = aurora_set_global
private let aurora_get_globalStandalone = aurora_get_global
private let aurora_route_sourceStandalone = aurora_route_source
private let aurora_velocity_curveStandalone = aurora_velocity_curve
private let aurora_holdStandalone = aurora_hold
private let aurora_clock_sourceStandalone = aurora_clock_source
private let aurora_clock_tempoStandalone = aurora_clock_tempo
private let aurora_record_startStandalone = aurora_record_start
private let aurora_record_stopStandalone = aurora_record_stop
private let aurora_recordingStandalone = aurora_recording
private let aurora_record_secondsStandalone = aurora_record_seconds
private let aurora_note_onStandalone = aurora_note_on
private let aurora_note_offStandalone = aurora_note_off
private let aurora_panicStandalone = aurora_panic
private let aurora_output_peakStandalone = aurora_output_peak
private let aurora_comp_grStandalone = aurora_comp_gr
private let aurora_copy_scopeStandalone = aurora_copy_scope
private let aurora_copy_modulationStandalone = aurora_copy_modulation
private let aurora_set_custom_wavetableStandalone = aurora_set_custom_wavetable
private let aurora_clear_custom_wavetableStandalone = aurora_clear_custom_wavetable
private let aurora_copy_wavetable_previewStandalone = aurora_copy_wavetable_preview
private let aurora_cpu_loadStandalone = aurora_cpu_load
private let aurora_active_voicesStandalone = aurora_active_voices
private let aurora_midi_event_countStandalone = aurora_midi_event_count
private let aurora_last_ccStandalone = aurora_last_cc
private let aurora_last_cc_sourceStandalone = aurora_last_cc_source
private let aurora_cc_countStandalone = aurora_cc_count
private let aurora_last_cc_snapshotStandalone = aurora_last_cc_snapshot
#endif
